#plot4
library("dplyr")
data<-read.delim("household_power_consumption.txt", sep=";")
data$date1<-paste(data$Date, data$Time, sep=" ")
data$Date<-strptime(data$date1, format="%d/%m/%Y %H:%M:%S")
data$Date<-as.POSIXct(data$Date)
data1<- filter(data,Date>=as.POSIXct("2007-02-01", format="%Y-%m-%d") & Date<as.POSIXct("2007-02-03", format="%Y-%m-%d"))

png("plot4.png", width=480, height=480, units="px")
par(mfrow=c(2,2))
plot(data1$Date,as.numeric(as.character(data1$Global_active_power)),type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(data1$Date,as.numeric(as.character(data1$Voltage)),type="l",xlab="datetime",ylab="Voltage")
with(data1, {
  plot(Date, Sub_metering_1, type="n",xlab="",ylab="Energy sub metering", ylim=c(1,38))
  points(Date, as.numeric(as.character(Sub_metering_1)), type="l")
  points(Date, as.numeric(as.character(Sub_metering_2)), type="l",col="red")
  points(Date, as.numeric(as.character(Sub_metering_3)), type="l",col="blue")
  legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1, col=c("black","red","blue"), box.lty=0,cex=1)})
plot(data1$Date, as.numeric(as.character(data1$Global_reactive_power)), ylab="Global_reactive_power", xlab="datetime", type="l")
dev.off()
